Ext.define('Module.pos.serviceInstance.model.ServiceStepInstance', {
    extend: 'Ext.data.Model',
    fields: [{ name: 'Id', type: 'int' },
        { name: 'Version', type: 'int' },
        { name: 'Active', type: 'boolean', defaultValue: true },
        { name: 'LastUpdate', type: 'date' },
        { name: 'UpdateBy', type: 'string' },
        { name: 'CreateDate', type: 'date' },
        { name: 'CreateBy', type: 'string' },
        { name: 'Name', type: 'string' },
        { name: 'Identifier', type: 'string' },
        { name: 'Duration', type: 'decimal' },
        { name: 'Description', type: 'string' },
        { name: 'Notes', type: 'string' },
        { name: 'Tool', type: 'string' },
        { name: 'Material', type: 'string' },
        { name: 'Purpose', type: 'string' },
        { name: 'Equipment', type: 'string' },
        { name: 'Actions', type: 'string' },
        { name: 'ActualStartTime', type: 'date' },
        { name: 'ActualEndTime', type: 'date' },
        { name: 'WorkerNumber', type: 'string' },
        { name: 'WorkerName', type: 'string' },
        { name: 'BayNumber', type: 'string' },
        { name: 'Status', type: 'string' },
        { name: 'Memo', type: 'string' }
    ],
    idProperty: 'Id'
});